name: Auto Commit for UserA

on:
  schedule:
    - cron: '0 3 * * *'  # Every day at 3:00 AM UTC
  workflow_dispatch:

jobs:
  sync:
    uses: ./.github/workflows/template-committer.yml
    with:
      target_user: usera
    secrets: inherit