name: Template Committer

on:
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout controller
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Install deps
        run: pip install pyyaml

      - name: Run sync script
        run: python auto_sync.py
        env:
          TOKEN_USERA: ${{ secrets.TOKEN_USERA }}
          TOKEN_USERB: ${{ secrets.TOKEN_USERB }}
